name: Docker Image CI

on:
  push:
    branches: [ "release/2.10.5" ]
  pull_request:
    branches: [ "release/2.10.5" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag dockerhub.com/tonytony1/airflow:2.10.5-$(date +%s)
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        push: true
        tags: airflow:2.10.5-$(date +%s)
